# Generated by Django 4.2.1 on 2023-05-04 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('lastname', models.CharField(max_length=20, verbose_name='lastname')),
                ('username', models.CharField(max_length=20, verbose_name='username')),
                ('email', models.EmailField(max_length=50, verbose_name='email')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='phone')),
                ('date_of_birth', models.DateField(max_length=20, verbose_name='date_of_birth')),
                ('description', models.CharField(max_length=200, null=True, verbose_name='description')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
